services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2  # Cache de dependências Maven
    command: ./mvnw spring-boot:run
    networks:
        - licitacao-net

  mariadb:
    image: mariadb:latest
    environment:
        MARIADB_DATABASE: gestaodb
        MARIADB_ROOT_PASSWORD: admin
        MARIADB_PASSWORD: admin
        MARIADB_USER: admin
    ports:
        - 3306:3306
    volumes:
        - mariadb_data:/var/lib/mysql        
    command:
        --max_allowed_packet=32505856
    networks:
        - licitacao-net		

networks:
    licitacao-net:
        driver: bridge

volumes:
    mariadb_data:  	